### ISSUE TITLE
Async gzip decoder panicking at assertion in bit.rs

### ISSUE THREAD

**Issue by KodrAus** [sile/libflate#10]
Hi there!

I'm working on using the new `WouldBlock` friendly gzip decoder in https://github.com/seanmonstar/reqwest/pull/165 and am running into a problem for some kinds of chunked responses.

I'm sure this is something I'm not doing correctly, so am just wondering what the below assertion that's failing is all about so I get a better idea of what I might be doing that's breaking it:

```
panicked at 'assertion failed: 32 - self.offset >= bitwidth', /$USER/.cargo/registry/src/libflate-0.1.9/src/bit.rs:130:8
```

I've found debugging this particular part of `libflate` a bit tricky because a lot of the functions are `#[inline(always)]` which confuses my poor debugger.

```
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:390
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic_new
             at /checkout/src/libstd/panicking.rs:553
   6: libflate::non_blocking::deflate::decode::BlockDecoder::decode_symbol::{{closure}}
             at ./<panic macros>:3
             at /$USER/.cargo/registry/src/libflate-0.1.9/src/bit.rs:109
             at /$USER/.cargo/registry/src/libflate-0.1.9/src/deflate/symbol.rs:242
             at /$USER/.cargo/registry/src/libflate-0.1.9/src/deflate/symbol.rs:211
             at /$USER/.cargo/registry/src/libflate-0.1.9/src/non_blocking/deflate/decode.rs:256
   7: <libflate::non_blocking::transaction::TransactionalBitReader<R>>::transaction
             at /$USER/.cargo/registry/src/libflate-0.1.9/src/non_blocking/transaction.rs:23
   8: libflate::non_blocking::deflate::decode::BlockDecoder::decode_symbol
             at /$USER/.cargo/registry/src/libflate-0.1.9/src/non_blocking/deflate/decode.rs:255
   9: libflate::non_blocking::deflate::decode::BlockDecoder::decode
             at /$USER/.cargo/registry/src/libflate-0.1.9/src/non_blocking/deflate/decode.rs:203
  10: <libflate::non_blocking::deflate::decode::Decoder<R> as std::io::Read>::read
             at /$USER/.cargo/registry/src/libflate-0.1.9/src/non_blocking/deflate/decode.rs:149
  11: <libflate::non_blocking::gzip::Decoder<R> as std::io::Read>::read
             at /$USER/.cargo/registry/src/libflate-0.1.9/src/non_blocking/gzip.rs:118
```

FWIW, the full backtrace:

```
panicked at 'assertion failed: 32 - self.offset >= bitwidth', /$USER/.cargo/registry/src/libflate-0.1.9/src/bit.rs:130:8
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:390
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic_new
             at /checkout/src/libstd/panicking.rs:553
   6: libflate::non_blocking::deflate::decode::BlockDecoder::decode_symbol::{{closure}}
             at ./<panic macros>:3
             at /$USER/.cargo/registry/src/libflate-0.1.9/src/bit.rs:109
             at /$USER/.cargo/registry/src/libflate-0.1.9/src/deflate/symbol.rs:242
             at /$USER/.cargo/registry/src/libflate-0.1.9/src/deflate/symbol.rs:211
             at /$USER/.cargo/registry/src/libflate-0.1.9/src/non_blocking/deflate/decode.rs:256
   7: <libflate::non_blocking::transaction::TransactionalBitReader<R>>::transaction
             at /$USER/.cargo/registry/src/libflate-0.1.9/src/non_blocking/transaction.rs:23
   8: libflate::non_blocking::deflate::decode::BlockDecoder::decode_symbol
             at /$USER/.cargo/registry/src/libflate-0.1.9/src/non_blocking/deflate/decode.rs:255
   9: libflate::non_blocking::deflate::decode::BlockDecoder::decode
             at /$USER/.cargo/registry/src/libflate-0.1.9/src/non_blocking/deflate/decode.rs:203
  10: <libflate::non_blocking::deflate::decode::Decoder<R> as std::io::Read>::read
             at /$USER/.cargo/registry/src/libflate-0.1.9/src/non_blocking/deflate/decode.rs:149
  11: <libflate::non_blocking::gzip::Decoder<R> as std::io::Read>::read
             at /$USER/.cargo/registry/src/libflate-0.1.9/src/non_blocking/gzip.rs:118
  12: <reqwest::async_impl::decoder::Gzip as futures::stream::Stream>::poll
             at src/async_impl/decoder.rs:178
  13: <reqwest::async_impl::decoder::Decoder as futures::stream::Stream>::poll
             at src/async_impl/decoder.rs:114
  14: <reqwest::async_impl::decoder::Decoder as futures::stream::Stream>::poll
             at src/async_impl/decoder.rs:118
  15: <futures::stream::concat::ConcatSafe<S> as futures::future::Future>::poll
             at /$USER/.cargo/registry/src/futures-0.1.14/src/stream/concat.rs:133
  16: <futures::stream::concat::Concat2<S> as futures::future::Future>::poll
             at /$USER/.cargo/registry/src/futures-0.1.14/src/stream/concat.rs:46
  17: <futures::future::chain::Chain<A, B, C>>::poll
             at /$USER/.cargo/registry/src/futures-0.1.14/src/future/chain.rs:32
  18: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
             at /$USER/.cargo/registry/src/futures-0.1.14/src/future/and_then.rs:32
  19: <futures::future::chain::Chain<A, B, C>>::poll
             at /$USER/.cargo/registry/src/futures-0.1.14/src/future/chain.rs:26
  20: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
             at /$USER/.cargo/registry/src/futures-0.1.14/src/future/and_then.rs:32
  21: <futures::task_impl::Spawn<F>>::poll_future_notify::{{closure}}
             at /$USER/.cargo/registry/src/futures-0.1.14/src/task_impl/mod.rs:291
  22: <futures::task_impl::Spawn<T>>::enter::{{closure}}
             at /$USER/.cargo/registry/src/futures-0.1.14/src/task_impl/mod.rs:352
  23: futures::task_impl::std::set
             at /$USER/.cargo/registry/src/futures-0.1.14/src/task_impl/std/mod.rs:90
  24: <futures::task_impl::Spawn<T>>::enter
             at /$USER/.cargo/registry/src/futures-0.1.14/src/task_impl/mod.rs:352
  25: <futures::task_impl::Spawn<F>>::poll_future_notify
             at /$USER/.cargo/registry/src/futures-0.1.14/src/task_impl/mod.rs:291
  26: tokio_core::reactor::Core::run::{{closure}}
             at /$USER/.cargo/registry/src/tokio-core-0.1.8/src/reactor/mod.rs:235
  27: <scoped_tls::ScopedKey<T>>::set
             at /$USER/.cargo/registry/src/scoped-tls-0.1.0/src/lib.rs:135
  28: tokio_core::reactor::Core::run
             at /$USER/.cargo/registry/src/tokio-core-0.1.8/src/reactor/mod.rs:234
  29: async::async_test_gzip_response
             at tests/async.rs:71
  30: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1477
             at /checkout/src/libcore/ops/function.rs:143
             at /checkout/src/libtest/lib.rs:138
  31: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
```

**Comment by sile** [comment]
Thank you for reporting this problem.

Typically, a failure of `debug_assert!` means there is a bug in `libflate`.
I would like to fix this problem, so I'm grateful if you can tell me how to
reproduce it.

**Comment by KodrAus** [comment]
No problem, in the `reqwest` PR I posted this is being reproduced in the `async_test_gzip_response` test. I think when the reader wrapped by `libflate` hits a `WouldBlock`.

I'll try come up with a simpler repro than that though.

**Comment by KodrAus** [comment]
So I haven't made a whole lot of progress, but threw some `println`s around the `debug_assert` and the assertion has the following properties before failing:

```
// This read succeeds
ready: read: 1
offset: 14, bitwidth: 1
offset: 15, bitwidth: 0
offset: 15, bitwidth: 3
offset: 18, bitwidth: 8

// This read fails
not ready: would block
offset: 18, bitwidth: 1
offset: 19, bitwidth: 0
offset: 19, bitwidth: 3
offset: 22, bitwidth: 12
panic!
```

So the inner reader is returning `WouldBlock`. But not all `WouldBlock` reads are failing.

If I simply remove [the `debug_assert` here](https://github.com/sile/libflate/blob/master/src/bit.rs#L130) then everything seems to work correctly.

**Comment by sile** [comment]
Thank you for your information!
I added a test (https://github.com/sile/libflate/commit/62ecaee4d0ad41535dffe0144c95226b51a21d10) for reproducing the problem and fixed it at the commit https://github.com/sile/libflate/commit/f9171cd3caf842853fd6e9406f814fcbe7b34e16.

**Comment by KodrAus** [comment]
Nice, thanks @sile! This looks like it's all fixed now.
